# Generated by Django 3.0.3 on 2021-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_auto_20210404_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='layout',
            field=models.CharField(choices=[('alt', 'alternating'), ('notalt', 'not-alternating'), ('big-centered-stream', 'big-centered-stream')], default='alt', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('center-photo', 'center-photo'), ('alt-photo', 'alt-photo'), ('big-center-photo', 'big-center-photo')], default='alt-photo', max_length=16),
        ),
    ]
