# Generated by Django 3.0.3 on 2021-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_gallerytextfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='credits',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
