# Generated by Django 3.0.3 on 2021-06-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_auto_20210518_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='credits',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
